#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -dpi 125 -yoffset 60 -xoffset 28 -line-padding 4 -columns 1 -width 25 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme "Sweet-Blue" -font "Noto Sans 11"
